### ISSUE TITLE
Tooltip break

### ISSUE THREAD

**Issue by dtlnor** [klimaleksus/stable-diffusion-webui-conditioning-highres-fix#1]
webui version ac085628540d0ec6a988fad93f5b8f2154209571
extension version f88e08cc273e2d2365be78bd2da8056d0e97b1e6
platform: windows 10, chrome

All the tooltip (the pop-up hint when mouse hover) from webui itself are broke after installing this extension

**Comment by aleksusklim** [comment]
OMG, I forgot `var`, thank you!
