### ISSUE TITLE
Not seeing a change

### ISSUE THREAD

**Issue by kalkal11** [klimaleksus/stable-diffusion-webui-conditioning-highres-fix#3]
Hi, this is highly likely user error but I'm seeing the exact same result whether or not I set a conditioning option or not -
this is off
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/110500565/202717789-61f7a182-5aac-40b7-9edb-55ee52b4f03f.png">

This is set to high -
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/110500565/202717958-a460e11b-3469-45e1-a20c-506c506a0843.png">

loading up the results onto a couple layers in photoshop shows that the results are identical (variance from xformers ignored) what do you think I'm doing wong?

**Comment by aleksusklim** [comment]
> v1-5-pruned-emaonly.ckpt

https://github.com/klimaleksus/stable-diffusion-webui-conditioning-highres-fix#faq

> **F.A.Q.**
> **It doesn't do anything at all!**
> Make sure you've loaded "sd-v1-5-inpainting" as your checkpoint. Also, watch the console, the script outputs line "Conditioning Highres.fix:" when it rewrites mask strength.
