### ISSUE TITLE
Is it possible to do the same thing without changing the models?

### ISSUE THREAD

**Issue by AndreyRGW** [klimaleksus/stable-diffusion-webui-conditioning-highres-fix#5]

**Comment by aleksusklim** [comment]
To do _what_?

**Comment by AndreyRGW** [comment]
> To do _what_?

Preserve similarity using highres fix on high denoising strenght values without changing the model to inpainting

**Comment by aleksusklim** [comment]
The closest what you can get is [Tile ControlNet](https://github.com/lllyasviel/ControlNet-v1-1-nightly#controlnet-11-tile), but seems that it cannot be used with Hires.fix specifically, without any prior control image.

You will have to load your lowres image in img2img.
Also, there is ControlNet Inpainting separate model, which can effectively turn any model into inpainting one, but without conditioning value.
